#!/bin/sh

module="lfs_ppd01"
device="lfs_ppd01"
mode="664"


/sbin/insmod ./$module.ko leds=0xAA $* || exit 1

rm -f /dev/$device

major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

mknod /dev/$device c $major 0



#group="staff"
#grep -q '^staff:' /etc/group || group="wheel"

#chgrp $group /dev/$device

chmod $mode /dev/$device



